name: example_chat_app
description: "A chat app example with Clean Architecture and BLoC."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
